spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_store
    username: root
    password: D0ga00g123@

  mail:
    host: smtp.gmail.com
    port: 587
    username: loc.pakirat.tech@gmail.com
    password: tmazpciuaxzpqkcw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
